apiVersion: batch/v1
kind: Job
metadata:
  name: doesNotMatter
spec:
  template:
    spec:
      containers:
        - name: install-packages
          envFrom:
            - configMapRef:
                name: http-proxy-cm
