openwhisk:
  whisk:
    ingress:
      apiHostName: 'whisk-ft.i2ec.top'
      domain: 'whisk-ft.i2ec.top'
      apiHostPort: 443
      apiHostProto: 'https'
      type: Standard
      annotations: {}
      auth:
        system: '789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP'
        guest: '23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP'
      useInternally: false

  nginx: {}

  affinity:
    enabled: false

  toleration:
    enabled: false

  invoker:
    options: '-Dwhisk.kubernetes.user-pod-node-affinity.enabled=false'
    # must use KCF as kind uses containerd as its container runtime
    containerFactory:
      impl: 'kubernetes'
