apiVersion: v1
kind: ConfigMap
metadata:
  name: http-proxy-cm
  namespace: faasit-system
data:
  http_proxy: proxy.i2ec.top:21087
  https_proxy: proxy.i2ec.top:21087
  no_proxy: 172.18.0.0/16,fc00:f853:ccd:e793::/64,*.i2ec.top,*.local,localhost,127.0.0.1,127.0.0.0/8,172.16.0.0/12,10.0.0.0/8,192.168.0.0/16,10.96.0.0/16,10.244.0.0/16,faasit-e2e-control-plane,.svc,.svc.cluster,.svc.cluster.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: http-proxy-cm
  namespace: openwhisk
data:
  http_proxy: proxy.i2ec.top:21087
  https_proxy: proxy.i2ec.top:21087
  no_proxy: 172.18.0.0/16,fc00:f853:ccd:e793::/64,*.i2ec.top,*.local,localhost,127.0.0.1,127.0.0.0/8,172.16.0.0/12,10.0.0.0/8,192.168.0.0/16,10.96.0.0/16,10.244.0.0/16,faasit-e2e-control-plane,.svc,.svc.cluster,.svc.cluster.local
